export const taskListDB=[
    {
        id: "01",
        type: "Upcoming",
        priority:"High",
        title:"first Task",
        description:"Create Task manager App",
        userID: ["01", "02", '05'],
    },
    {
        id: "02",
        type: "Upcoming",
        priority:"Medium",
        title:"printer settings",
        description:"When an unknown printer took a galley of type and scrambled it to make a type specimen book",
        userID: ["04"],
    },
    {
        id: "03",
        type: "Upcoming",
        priority:"High",
        title:"desktop publishing",
        description:"Many desktop publishing packages and web page editors now use Lorem",
        userID: ["02"],
    },
    {
        id: "04",
        type: "Upcoming",
        priority:"Medium",
        title:"Passage using",
        description:"If you are going to use a passage of Lorem Ipsum..",
        userID: ["05"],
    },
    {
        id: "05",
        type: "Upcoming",
        priority:"High",
        title:"Latin literature",
        description:"It has roots in a piece of classNameical Latin literature from 45 BC, making it over 2000 years old.",
        userID: ["03"],
    },    

    {
        id: "06",
        type: "In Progress",
        priority:"Low",
        title:"Design",
        description:"Develop the architecture and design of the software.",
        userID: ["05"],
    },
    {
        id: "07",
        type: "In Progress",
        priority:"High",
        title:"Test",
        description:"Test the software to ensure it meets the requirements.",
        userID: ["04"],
    },
    {
        id: "08",
        type: "In Progress",
        priority:"Low",
        title:"Design",
        description:"Install the software in the environment and make it available to users.",
        userID: ["03"],
    },
    {
        id: "09",
        type: "In Progress",
        priority:"Medium",
        title:"Test",
        description:"Design and construction of negative tests",
        userID: ["01"],
    },
    {
        id: "10",
        type: "Completed",
        priority:"High",
        title:"Test",
        description:"Increased automation of tests",
        userID: ["03"],
    },
    {
        id: "11",
        type: "Completed",
        priority:"Low",
        title:"Design",
        description:"Design and construction of limit tests and exception tests",
        userID: ["02"],
    },
    {
        id: "12",
        type: "Completed",
        priority:"High",
        title:"Development",
        description:"Code development and review",
        userID: ["01"],
    },
    {
        id: "13",
        type: "Completed",
        priority:"Medium",
        title:"Deployment",
        description:"Deployment automation",
        userID: ["04"],
    },
    {
        id: "14",
        type: "Completed",
        priority:"Low",
        title:"Design",
        description:"Prepare the remaining documentation",
        userID: ["06"],
    },
    {
        id: "15",
        type: "Completed",
        priority:"<ediu,>",
        title:"Test",
        description:"Extend the test infrastructure",
        userID: ["05"],
    },

]