export const taskList=[
    {
        id: "01",
        type: "Upcoming",
        title:"first Task",
        description:"Create Task manager App",
        userID: "01",
        user:"https://bootdey.com/img/Content/avatar/avatar1.png",
    },
    {
        id: "02",
        type: "Upcoming",
        title:"printer settings",
        description:"When an unknown printer took a galley of type and scrambled it to make a type specimen book",
        userID: "04",
        user:"https://bootdey.com/img/Content/avatar/avatar4.png",
    },
    {
        id: "03",
        type: "Upcoming",
        title:"desktop publishing",
        description:"Many desktop publishing packages and web page editors now use Lorem",
        userID: "02",
        user:"https://bootdey.com/img/Content/avatar/avatar2.png",
    },
    {
        id: "04",
        type: "Upcoming",
        title:"Passage using",
        description:"If you are going to use a passage of Lorem Ipsum..",
        userID: "05",
        user:"https://bootdey.com/img/Content/avatar/avatar5.png",
    },
    {
        id: "05",
        type: "Upcoming",
        title:"Latin literature",
        description:"It has roots in a piece of classNameical Latin literature from 45 BC, making it over 2000 years old.",
        userID: "03",
        user:"https://bootdey.com/img/Content/avatar/avatar3.png",
    },
    

    {
        id: "06",
        type: "In Progress",
        title:"Design",
        description:"Develop the architecture and design of the software.",
        userID: "05",
        user:"https://bootdey.com/img/Content/avatar/avatar5.png",
    },
    {
        id: "07",
        type: "In Progress",
        title:"Test",
        description:"Test the software to ensure it meets the requirements.",
        userID: "04",
        user:"https://bootdey.com/img/Content/avatar/avatar4.png",
    },
    {
        id: "08",
        type: "In Progress",
        title:"Design",
        description:"Install the software in the environment and make it available to users.",
        userID: "03",
        user:"https://bootdey.com/img/Content/avatar/avatar3.png",
    },
    {
        id: "09",
        type: "In Progress",
        title:"Test",
        description:"Design and construction of negative tests",
        userID: "01",
        user:"https://bootdey.com/img/Content/avatar/avatar1.png",
    },
    {
        id: "10",
        type: "Completed",
        title:"Test",
        description:"Increased automation of tests",
        userID: "03",
        user:"https://bootdey.com/img/Content/avatar/avatar3.png",
    },
    {
        id: "11",
        type: "Completed",
        title:"Design",
        description:"Design and construction of limit tests and exception tests",
        userID: "02",
        user:"https://bootdey.com/img/Content/avatar/avatar2.png",
    },
    {
        id: "12",
        type: "Completed",
        title:"Development",
        description:"Code development and review",
        userID: "01",
        user:"https://bootdey.com/img/Content/avatar/avatar1.png",
    },
    {
        id: "13",
        type: "Completed",
        title:"Deployment",
        description:"Deployment automation",
        userID: "04",
        user:"https://bootdey.com/img/Content/avatar/avatar4.png",
    },
    {
        id: "14",
        type: "Completed",
        title:"Design",
        description:"Prepare the remaining documentation",
        userID: "06",
        user:"https://bootdey.com/img/Content/avatar/avatar6.png",
    },
    {
        id: "15",
        type: "Completed",
        title:"Test",
        description:"Extend the test infrastructure",
        userID: "05",
        user:"https://bootdey.com/img/Content/avatar/avatar5.png",
    },

]